### ISSUE TITLE
Java version

### ISSUE THREAD

**Issue by YenniferC** [Baseform/Baseform-Epanet-Java-Library#14]
I am trying to run the AwareEpanet.exe but it says i do not have Java, even though I do have, is there an special version which I should download? any compatibility issue?
Thank you.

**Comment by acastroceit** [comment]
Same problem here

**Comment by Baseform** [comment]
The ".exe" build is almost 10 years old, available more as a demo of a GUI for the library code.
It should detect a normal install of Java on windows, older versions work fine. Problems might be related to a combination of Java installation method, PC architecture (win32 / win64), ...

We've just tested installing Java JRE 7 on windows XP and it works: Java 7 can be found at https://www.oracle.com/in/java/technologies/javase/javase7-archive-downloads.html

Also, just tested on Windows 10, following the link to https://www.java.com/en/ and installing the latest version and running AwareEpanet.exe, also did work.
