### ISSUE TITLE
How to run the network

### ISSUE THREAD

**Issue by burakgulmez** [Baseform/Baseform-Epanet-Java-Library#7]
I made a simple network. The code is here(a simple code):

``` java
public class Main {
    public static void main(String[] args) throws ENException {
        // TODO Auto-generated method stub
        int i;
        //File input = new File("input.inp");
        //File output = new File("epanet_output");
        //EPATool epa = new EPATool();      
        Network network = new Network();        
        Node[] node = new Node[7];
        Link[] pipe = new Link[8];      
        Tank tank = new Tank();
        tank.setId("0");
        tank.setElevation(210);
        network.addTank("0", tank);     
        for(i=1; i<7; i++){
            node[i] = new Node();
        }       
        node[1].setElevation(150);
        node[1].setInitDemand(100);
        node[2].setElevation(160);
        node[2].setInitDemand(100);
        node[3].setElevation(155);
        node[3].setInitDemand(120);
        node[4].setElevation(150);
        node[4].setInitDemand(270);
        node[5].setElevation(165);
        node[5].setInitDemand(330);
        node[6].setElevation(160);
        node[6].setInitDemand(200);     
        for(i=0; i<8; i++){
            pipe[i] = new Link();
            pipe[i].setLenght(1000);            
        }   
        pipe[0].setFirst(tank);
        pipe[0].setSecond(node[1]);
        //System.out.println(pipe[0].getFirst());
        pipe[1].setFirst(node[1]);
        pipe[1].setSecond(node[2]);
        pipe[2].setFirst(node[1]);
        pipe[2].setSecond(node[3]);
        pipe[3].setFirst(node[3]);
        pipe[3].setSecond(node[4]);
        pipe[4].setFirst(node[3]);
        pipe[4].setSecond(node[5]);
        pipe[5].setFirst(node[5]);
        pipe[5].setSecond(node[6]);
        pipe[6].setFirst(node[2]);
        pipe[6].setSecond(node[4]);
        pipe[7].setFirst(node[4]);
        pipe[7].setSecond(node[6]);     
        for(i=1;i<7;i++){
            network.addJunction(Integer.toString(i), node[i]);
        }
        for(i=0;i<8;i++){
            network.addPipe(Integer.toString(i), pipe[i]);
        }



    }
}
```

I created a network with pipes, nodes and a tank. How can I run this network and get pipes flow and nodes pressure? I need the flow and pressure values.

**Comment by Baseform** [comment]
There are a number of different ways to achieve what you need which we expect to document soon. Something like this should work (please excuse the ugly code):
//please note the parse step which is needed for internal preparation of the network.

        NullParser nP = (NullParser) InputParser.create(Network.FileType.NULL_FILE, log);
        nP.parse(net, null);

        File hydFile = File.createTempFile("hydSim", "bin");
        //// Simulate hydraulics
        HydraulicSim hydSim = new HydraulicSim(net, log);
        hydSim.simulate(hydFile);

        // Create an hydraulic reader.
        HydraulicReader hydReader = new HydraulicReader(new RandomAccessFile(hydFile, "r"));

        // Get the nodes heads in the specified report times.
        for (long time = pMap.getRstart(); time <= pMap.getDuration(); time += pMap.getRstep()) {
            AwareStep step = (AwareStep) hydReader.getStep((int) time);
            System.out.print(" Time : " + Utilities.getClockTime(step.getTime()) + ", nodes heads : ");

            int i = 0;
            for (Node node : net.getNodes()) 
                System.out.print(String.format("%.2f\t", step.getNodeHead(i++, node, null)));
            System.out.println();
        }

        hydReader.close();

**Comment by burakgulmez** [comment]
this gives error. (pMap cannot be resolved)
```java
for (long time = pMap.getRstart(); time <= pMap.getDuration(); time += pMap.getRstep()) {
```

**Comment by Baseform** [comment]
Right.
Bellow a revised/unified example:

/*
 * Copyright (C) 2015  Addition, Lda. (addition at addition dot pt)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/.
 */

package test;

import org.addition.epanet.hydraulic.HydraulicSim;
import org.addition.epanet.hydraulic.io.AwareStep;
import org.addition.epanet.hydraulic.io.HydraulicReader;
import org.addition.epanet.network.Network;
import org.addition.epanet.network.PropertiesMap;
import org.addition.epanet.network.io.input.InputParser;
import org.addition.epanet.network.io.input.NullParser;
import org.addition.epanet.network.structures.Link;
import org.addition.epanet.network.structures.Node;
import org.addition.epanet.network.structures.Tank;
import org.addition.epanet.util.ENException;
import org.addition.epanet.util.Utilities;

import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Logger;

public class SampleOOPNetwork2 {
    public static void main(String[] args) throws IOException, ENException {
        int i;

        Network network = new Network();

        //Tank
        Tank tank = new Tank();
        tank.setElevation(210);
        network.addTank("0", tank);

        //Nodes
        Node[] node = new Node[7];
        for(i=1; i<7; i++){
            node[i] = new Node();
        }
        node[1].setElevation(150);
        node[1].setInitDemand(100);
        node[2].setElevation(160);
        node[2].setInitDemand(100);
        node[3].setElevation(155);
        node[3].setInitDemand(120);
        node[4].setElevation(150);
        node[4].setInitDemand(270);
        node[5].setElevation(165);
        node[5].setInitDemand(330);
        node[6].setElevation(160);
        node[6].setInitDemand(200);

        //Links
        Link[] pipe = new Link[8];
        for(i=0; i<8; i++){
            pipe[i] = new Link();
            pipe[i].setLenght(1000);
        }
        pipe[0].setFirst(tank);
        pipe[0].setSecond(node[1]);
        pipe[1].setFirst(node[1]);
        pipe[1].setSecond(node[2]);
        pipe[2].setFirst(node[1]);
        pipe[2].setSecond(node[3]);
        pipe[3].setFirst(node[3]);
        pipe[3].setSecond(node[4]);
        pipe[4].setFirst(node[3]);
        pipe[4].setSecond(node[5]);
        pipe[5].setFirst(node[5]);
        pipe[5].setSecond(node[6]);
        pipe[6].setFirst(node[2]);
        pipe[6].setSecond(node[4]);
        pipe[7].setFirst(node[4]);
        pipe[7].setSecond(node[6]);
        for(i=1;i<7;i++){
            network.addJunction(Integer.toString(i), node[i]);
        }
        for(i=0;i<8;i++){
            network.addPipe(Integer.toString(i), pipe[i]);
        }


        //Prepare Network
        Logger log = Logger.getLogger(Sample_ReadSimulationData.class.toString());
        NullParser nP = (NullParser) InputParser.create(Network.FileType.NULL_FILE, log);
        assert nP != null;
        nP.parse(network, null);

        //// Simulate hydraulics
        File hydFile = File.createTempFile("hydSim", "bin");
        HydraulicSim hydSim = new HydraulicSim(network, log);
        hydSim.simulate(hydFile);

        // Read hydraulic results
        PropertiesMap pMap = network.getPropertiesMap();
        HydraulicReader hydReader = new HydraulicReader(new RandomAccessFile(hydFile, "r"));
        for (long time = pMap.getRstart(); time <= pMap.getDuration(); time += pMap.getRstep()) {
            AwareStep step = hydReader.getStep((int) time);
            System.out.print("Time : " + Utilities.getClockTime(step.getTime()) + ", nodes heads : ");

            i=0;
            for (Node inode : network.getNodes())
                System.out.print(String.format("%.2f\t", step.getNodeHead(i++, inode, null)));
            System.out.println();
        }

        hydReader.close();
    }
}

**Comment by Baseform** [comment]
And here is an example for a dynamic/streaming simulation:

/*
 * Copyright (C) 2015  Addition, Lda. (addition at addition dot pt)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/.
 */

package test;

import org.addition.epanet.hydraulic.HydraulicSim;
import org.addition.epanet.hydraulic.io.AwareStep;
import org.addition.epanet.hydraulic.io.HydraulicReader;
import org.addition.epanet.hydraulic.structures.SimulationNode;
import org.addition.epanet.network.FieldsMap;
import org.addition.epanet.network.Network;
import org.addition.epanet.network.PropertiesMap;
import org.addition.epanet.network.io.input.InputParser;
import org.addition.epanet.network.io.input.NullParser;
import org.addition.epanet.network.structures.Link;
import org.addition.epanet.network.structures.Node;
import org.addition.epanet.network.structures.Tank;
import org.addition.epanet.util.ENException;
import org.addition.epanet.util.Utilities;

import java.io.DataOutput;
import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Logger;

public class SampleOOPNetworkDyn2 {
    public static void main(String[] args) throws IOException, ENException {
        int i;

        Network network = new Network();

        //Tank
        Tank tank = new Tank();
        tank.setElevation(210);
        network.addTank("0", tank);

        //Nodes
        Node[] node = new Node[7];
        for(i=1; i<7; i++){
            node[i] = new Node();
        }
        node[1].setElevation(150);
        node[1].setInitDemand(100);
        node[2].setElevation(160);
        node[2].setInitDemand(100);
        node[3].setElevation(155);
        node[3].setInitDemand(120);
        node[4].setElevation(150);
        node[4].setInitDemand(270);
        node[5].setElevation(165);
        node[5].setInitDemand(330);
        node[6].setElevation(160);
        node[6].setInitDemand(200);

        //Links
        Link[] pipe = new Link[8];
        for(i=0; i<8; i++){
            pipe[i] = new Link();
            pipe[i].setLenght(1000);
        }
        pipe[0].setFirst(tank);
        pipe[0].setSecond(node[1]);
        pipe[1].setFirst(node[1]);
        pipe[1].setSecond(node[2]);
        pipe[2].setFirst(node[1]);
        pipe[2].setSecond(node[3]);
        pipe[3].setFirst(node[3]);
        pipe[3].setSecond(node[4]);
        pipe[4].setFirst(node[3]);
        pipe[4].setSecond(node[5]);
        pipe[5].setFirst(node[5]);
        pipe[5].setSecond(node[6]);
        pipe[6].setFirst(node[2]);
        pipe[6].setSecond(node[4]);
        pipe[7].setFirst(node[4]);
        pipe[7].setSecond(node[6]);
        for(i=1;i<7;i++){
            network.addJunction(Integer.toString(i), node[i]);
        }
        for(i=0;i<8;i++){
            network.addPipe(Integer.toString(i), pipe[i]);
        }


        //Prepare Network
        Logger log = Logger.getLogger(Sample_ReadSimulationData.class.toString());
        NullParser nP = (NullParser) InputParser.create(Network.FileType.NULL_FILE, log);
        assert nP != null;
        nP.parse(network, null);

        //// Simulate hydraulics and get streaming/dynamic results
        new DynamicSimulation(network, log).simulate();
    }

    static class DynamicSimulation extends HydraulicSim {

        public DynamicSimulation(Network net, Logger log) throws ENException {
            super(net, log);
            logger = log;
        }

        public void simulate() throws ENException, IOException {
            super.simulate((DataOutput) null);
        }

        @Override
        protected long nextHyd() throws ENException, IOException {
            long l1 = super.nextHyd();
            System.out.print("Time : " + Utilities.getClockTime(l1) + ", nodes heads : ");
            for (SimulationNode node : getnNodes()) {
                double H = fMap.revertUnit(FieldsMap.Type.HEAD, node.getSimHead());
                System.out.print(String.format("%.2f\t", H));
            }
            return l1;
        }
    }
}

**Comment by burakgulmez** [comment]
gives error again
Logger log = Logger.getLogger(**Sample_ReadSimulationData**.class.toString());
It does not understand : Sample_ReadSimulationData, and does not give a code suggestion. Should I change this?

**Comment by Baseform** [comment]
Right. Replace "Sample_ReadSimulationData" with the name of the class – "SampleOOPNetworkDyn2", for instance. Feel free to contact us directly by email if it sounds easier.
