### ISSUE TITLE
Flow sign ommited in results: No information about flow direction

### ISSUE THREAD

**Issue by petacoder75** [Baseform/Baseform-Epanet-Java-Library#8]
In the *.links.out file the flow is allways represented without sign as an absolute value. That means that you do not have numerical way to know the direction of the flow.

When representing a pipe in original Epanet, if the pipe is defined with nodes A to B, a positive flow means A to B direction. A negative flow means B to A direction.

In this library this effect seems to be ignored and generates a problem when simulating some situations where the flow changes the direction.

Am I right? How can we solve it?

**Comment by Baseform** [comment]
Hi. The file you refer to looks like one output of the EpaTool.java UI class: the one in plain text. It is generated based on the LinkVariableType enum which calls AwareStep QL property for each link. AwareStep is a helper class for binary storing of simulation data which is also available dynamically, during the simulation on SimulationLink object instances.
There, on SimulationLink, the value is stored on:
protected double flow;           // Epanet 'Q[k]', link flow value

You are right that this member can contain  positive or negative flows, based on the direction on the modeled network. Can you send us the network you are using and highlight the link and timestep where the results seem wrong. On our testing everything looks fine.
[you can use baseform.com general contact]

Thanks.

**Comment by petacoder75** [comment]
You can use any network you have and make two differente simulations:

- For a specific pipe defined from node A to node B, run simulation and look at the flow value. 
- For the same pipe, revert nodes. Now the pipe is defined from B to A. Simulate again and the Flow should have the same value with different sign. The problem is that you export the flow value as an absolute value and the result is the same.

I think the problem is here:

public double getValue(PropertiesMap.FormType formType, FieldsMap fmap, AwareStep step, Link link, int index) throws ENException {
            switch (this) {
...
                case FLOW:
                    return step != null ? ****Math.abs**(step.getLinkFlow(index, link, fmap))** : 0;
...
            }
        }

**Comment by Baseform** [comment]
Hey. Sorry for the delayed answer and thanks for finding this. Fixed.
