### ISSUE TITLE
How to Run hydraulic Single Step Simulation

### ISSUE THREAD

**Issue by Mrebrahimi87** [Baseform/Baseform-Epanet-Java-Library#9]
I want to run hydraulic simulation with following Step:
1- Read an .inp file as input network
2- Put number of links and number of nodes in NomLinks and NomNodes
3- Set some pipes status(closed or open), and get start node and finish node index of these pipes
4- Set emitter of some Nodes by using node index
5- Run a single step hydraulic simulation and save each nodes pressure and index in an Array
 
I wrote this code in C format of Epanet. now, I want it in java format and there is no user manual.

#include "epanet2.h"
#include <cstdlib>
#include <iostream>
#include<fstream>
#include <stdlib.h>
#include <time.h>
#include <algorithm>
using namespace std;

int main()
{
	int NumLinks,NumNodesm,PipeIndex,t;
	int NumNodes,i,id;
	float SumP , P ;

	// Step 1
	ENopen("I.inp", "GR.rpt", "");

	// Step 2
	ENgetcount(EN_NODECOUNT, &NumNodes);
	ENgetcount(EN_LINKCOUNT, &NumLinks);

	// Step 3 ,4
	int SNode, FNode;
	ENsetlinkvalue(PipeIndex, EN_INITSTATUS, 0);
	ENgetlinknodes(PipeIndex, &SNode, &FNode);
	ENsetnodevalue(SNode, EN_EMITTER, 1);
	ENsetnodevalue(FNode, EN_EMITTER, 1);

	// Step 5
	ENopenH();
	ENinitH(0);
	ENrunH(&t);
	ENgetcount(EN_NODECOUNT, &NumNodes);
	for (i = 1; i <= NumNodes; i++)
		{
			ENgetnodevalue(i, EN_PRESSURE, &P);
			SumP = SumP + P;
		}

	getchar();
	return 0;
}

**Comment by Baseform** [comment]
take a look at this issue:
https://github.com/Baseform/Baseform-Epanet-Java-Library/issues/7

**Comment by Mrebrahimi87** [comment]
@Baseform Thanks for your response.
In the issue you mentioned, network was defined with user but I want to load network from .inp file.
Also, I want to run single hydraulic simulation.
Due to there is no user guide for Java version of Epanet, I faced problems for loading .inp file and running it. would you please send me a code for doing these work.

**Comment by hibrahimates** [comment]
I m looking for same codes with @Mrebrahimi87.
 @Baseform could you please help us?
Or is there any user manual for java-epaNet?
